openapi: 3.0.1
info:
  title: JavaCRUD API
  description: JavaCRUD API
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
tags:
  - name: users
    description: "Operations about user"

#    externalDocs:
#      description: "Find out more about our store"
#      url: "http://swagger.io"
paths:
  /users:
    get:
      tags:
        - users
      summary: Get User list
      operationId: getAll
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: 'Page'
    post:
      tags:
        - users
      summary: Create a user
      operationId: create
      requestBody:
        description: create user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequestOas'
        required: true
      responses:
        200:
          description: OK
        400:
          description: Failed
  /users/{id}:
    get:
      tags:
        - users
      summary: Get user by Id
      description: ""
      operationId: getById
      parameters:
        - name: id
          description: user id
          schema:
            type: integer
            format: int64
          in: path
          required: true
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadUserResponseOas'
    put:
      tags:
        - users
      summary: Updated user
      description: ""
      operationId: update
      parameters:
        - name: id
          description: user id
          schema:
            type: integer
            format: int64
          in: path
          required: true
      requestBody:
        description: user request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequestOas'
        required: true
      responses:
        200:
          description: successful operation
    delete:
      tags:
        - users
      summary: Delete user by ID
      description: For valid response try integer IDs with positive integer value.
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          schema:
            type: integer
            minimum: 1.0
            format: int64
          description: ID of the company that needs to be deleted
          required: true
      responses:
        200:
          description: successful operation

components:
  schemas:
    CreateUserRequestOas:
      type: object
      properties:
        userName:
          type: string
          example: user name
        password:
          type: string
          example: password1@
        Number:
          type: string
          example: 010-1111-2222
    UpdateUserRequestOas:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userName:
          type: string
          example: user name
        password:
          type: string
          example: password1@
        Number:
          type: string
          example: 010-1111-2222
    ReadUserResponseOas:
      type: object
      properties:
        id:
          type: integer
          format: int64
        userName:
          type: string
          example: user name
        Number:
          type: string
          example: 010-1111-2222